# Generated by Django 4.2.3 on 2024-12-29 13:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_admin_geomap


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Активность',
                'verbose_name_plural': 'Активности',
                'db_table': 'activity',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(verbose_name='Дата заезда')),
                ('check_out', models.DateField(verbose_name='Дата выезда')),
                ('status', models.CharField(choices=[('paid', 'paid'), ('booked', 'booked'), ('conditionally', 'conditionally')], max_length=13, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'db_table': 'cities',
            },
        ),
        migrations.CreateModel(
            name='CityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cities', verbose_name='Загрузить изображение')),
            ],
            options={
                'verbose_name': 'Изображение города',
                'verbose_name_plural': 'Изображение городов',
                'db_table': 'city_images',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
                'db_table': 'countries',
            },
        ),
        migrations.CreateModel(
            name='CountryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='countries', verbose_name='Загрузить изображение')),
            ],
            options={
                'verbose_name': 'Изображение страны',
                'verbose_name_plural': 'Изображение стран',
                'db_table': 'country_images',
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('main_image', models.ImageField(upload_to='destination/', verbose_name='Главное изображение')),
                ('active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Пункт',
                'verbose_name_plural': 'Пункты',
                'db_table': 'destination',
            },
        ),
        migrations.CreateModel(
            name='DestinationImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='destination/', verbose_name='Загрузить изображение')),
            ],
            options={
                'verbose_name': 'Изображение пункта',
                'verbose_name_plural': 'Изображение пунктов',
                'db_table': 'destination_images',
            },
        ),
        migrations.CreateModel(
            name='DestinationRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Рейтинг')),
            ],
            options={
                'verbose_name': 'Рейтинг пункта',
                'verbose_name_plural': 'Рейтинги пунктов',
                'db_table': 'destination_rating',
            },
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
                'db_table': 'itinerary',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название локации')),
                ('lon', models.FloatField(verbose_name='Долгота')),
                ('lat', models.FloatField(verbose_name='Широта')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
                'db_table': 'locations',
            },
            bases=(models.Model, django_admin_geomap.GeoItem),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Область',
                'verbose_name_plural': 'Области',
                'db_table': 'regions',
            },
        ),
        migrations.CreateModel(
            name='RegionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='regions', verbose_name='Загрузить изображение')),
            ],
            options={
                'verbose_name': 'Изображение региона',
                'verbose_name_plural': 'Изображение регионов',
                'db_table': 'region_images',
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название тура')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date_start', models.DateTimeField(verbose_name='Дата начала')),
                ('duration_date', models.CharField(max_length=255, verbose_name='Длительность')),
                ('total_distance', models.FloatField(verbose_name='Итоговая дистанция')),
                ('notes', models.TextField(verbose_name='Примечания')),
                ('video', models.URLField(verbose_name='Ссылка на видео')),
                ('main_image', models.ImageField(upload_to='tour/', verbose_name='Главное изображение')),
            ],
            options={
                'verbose_name': 'Тур',
                'verbose_name_plural': 'Туры',
                'db_table': 'tour',
            },
        ),
        migrations.CreateModel(
            name='TourComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Комментарий к туру',
                'verbose_name_plural': 'Комментарии к туру',
                'db_table': 'tour_comments',
            },
        ),
        migrations.CreateModel(
            name='TourCommentPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='commentImages', verbose_name='Загрузить изображение')),
            ],
            options={
                'verbose_name': 'Изображение комментария',
                'verbose_name_plural': 'Изображение комментариев',
                'db_table': 'comment_images',
            },
        ),
        migrations.CreateModel(
            name='TourDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(verbose_name='Номер дня')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('main_image', models.ImageField(null=True, upload_to='tour/', verbose_name='Главное изображение')),
                ('car_range', models.PositiveIntegerField(null=True, verbose_name='Длина пути на машине')),
                ('tracking_range', models.PositiveIntegerField(null=True, verbose_name='Длина пути пешком')),
                ('height_difference', models.CharField(max_length=255, null=True, verbose_name='Перепад высоты')),
                ('weather', models.CharField(max_length=255, verbose_name='Погода')),
                ('weather_date', models.DateField(verbose_name='Дата погоды')),
                ('entertainment', models.CharField(max_length=255, verbose_name='Развлечения')),
                ('details', models.TextField(verbose_name='Детали')),
            ],
            options={
                'verbose_name': 'День тура',
                'verbose_name_plural': 'Дни тура',
                'db_table': 'tour_day',
            },
        ),
        migrations.CreateModel(
            name='TourPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='commentImages', verbose_name='Загрузить изображение')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'db_table': 'tour_images',
            },
        ),
        migrations.CreateModel(
            name='TypeOfTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='Сложность')),
            ],
            options={
                'verbose_name': 'Сложность Тура',
                'verbose_name_plural': 'Сложности Туров',
                'db_table': 'level_of tour',
            },
        ),
        migrations.CreateModel(
            name='TourRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
                ('tour_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.tour', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Рейтинг тура',
                'verbose_name_plural': 'Рейтинги туров',
                'db_table': 'tour_rating',
            },
        ),
    ]
