# Generated by Django 4.2.3 on 2024-04-13 15:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_admin_geomap


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название отели')),
                ('description', models.TextField(verbose_name='Описание')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Отель',
                'verbose_name_plural': 'Отели',
                'db_table': 'accommodations',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'db_table': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
                'db_table': 'countries',
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('main_image', models.ImageField(upload_to='destination/', verbose_name='Главное изображение')),
                ('weather', models.CharField(max_length=255, verbose_name='Погода')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Пункт',
                'verbose_name_plural': 'Пункты',
                'db_table': 'destination',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название локации')),
                ('lon', models.FloatField(verbose_name='Долгота')),
                ('lat', models.FloatField(verbose_name='Широта')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
                'db_table': 'locations',
            },
            bases=(models.Model, django_admin_geomap.GeoItem),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.country')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tour.location', verbose_name='Локация')),
            ],
            options={
                'verbose_name': 'Область',
                'verbose_name_plural': 'Области',
                'db_table': 'regions',
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название тура')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date_start', models.DateTimeField(verbose_name='Дата начала')),
                ('duration_date', models.CharField(max_length=255, verbose_name='Длительность')),
                ('distance', models.FloatField(verbose_name='Дистанция')),
                ('altitude', models.CharField(max_length=255, verbose_name='Перепад высоты')),
                ('weather', models.CharField(max_length=255, verbose_name='Погода')),
                ('notes', models.TextField(verbose_name='Примечания')),
                ('video', models.URLField(verbose_name='Ссылка на видео')),
                ('main_image', models.ImageField(upload_to='tour/', verbose_name='Главное изображение')),
                ('geomap_latitude', models.CharField(blank=True, max_length=255, null=True, verbose_name='Широта')),
                ('geomap_longitude', models.CharField(blank=True, max_length=255, null=True, verbose_name='Долгота')),
                ('destinations', models.ManyToManyField(related_name='tour', to='tour.destination', verbose_name='Пункты')),
                ('excludes', models.ManyToManyField(to='categories.excludes', verbose_name='Исключения')),
                ('health_information', models.ManyToManyField(to='categories.health', verbose_name='Информация о здоровье')),
                ('includes', models.ManyToManyField(to='categories.includes', verbose_name='Включения')),
                ('personal_gear', models.ManyToManyField(to='categories.gear', verbose_name='Снаряжение')),
            ],
            options={
                'verbose_name': 'Тур',
                'verbose_name_plural': 'Туры',
                'db_table': 'tour',
            },
        ),
        migrations.CreateModel(
            name='TourComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tour.tourcomment')),
                ('tour_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.tour', verbose_name='Тур')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Комментарий к туру',
                'verbose_name_plural': 'Комментарии к туру',
                'db_table': 'tour_comments',
            },
        ),
        migrations.CreateModel(
            name='TypeOfTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Тип Тура',
                'verbose_name_plural': 'Типы Туров',
                'db_table': 'type_of tour',
            },
        ),
        migrations.CreateModel(
            name='TourRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
                ('tour_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.tour', verbose_name='Тур')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Рейтинг тура',
                'verbose_name_plural': 'Рейтинги туров',
                'db_table': 'tour_rating',
            },
        ),
        migrations.CreateModel(
            name='TourPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='commentImages', verbose_name='Загрузить изображение')),
                ('tour_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.tour', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'db_table': 'tour_images',
            },
        ),
        migrations.CreateModel(
            name='TourCommentPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='commentImages', verbose_name='Загрузить изображение')),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tour.tourcomment', verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Изображение комментария',
                'verbose_name_plural': 'Изображение комментариев',
                'db_table': 'comment_images',
            },
        ),
        migrations.AddField(
            model_name='tour',
            name='type_of',
            field=models.ManyToManyField(to='tour.typeoftour', verbose_name='Сложность'),
        ),
        migrations.AddField(
            model_name='tour',
            name='visa_information',
            field=models.ManyToManyField(to='categories.visa', verbose_name='Информация о визе'),
        ),
        migrations.CreateModel(
            name='RegionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='regions', verbose_name='Загрузить изображение')),
                ('region_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tour.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Изображение региона',
                'verbose_name_plural': 'Изображение регионов',
                'db_table': 'region_images',
            },
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tour.accommodation', verbose_name='Проживание')),
                ('entertainment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='categories.entertainment', verbose_name='Развлечения')),
                ('meals', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='categories.meal', verbose_name='Еда')),
                ('tour_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.tour', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
                'db_table': 'itinerary',
            },
        ),
        migrations.CreateModel(
            name='DestinationRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Рейтинг')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='tour.destination')),
            ],
            options={
                'verbose_name': 'Рейтинг пункта',
                'verbose_name_plural': 'Рейтинги пунктов',
                'db_table': 'destination_rating',
            },
        ),
        migrations.CreateModel(
            name='DestinationImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='destination/', verbose_name='Загрузить изображение')),
                ('destination_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tour.destination', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Изображение пункта',
                'verbose_name_plural': 'Изображение пунктов',
                'db_table': 'destination_images',
            },
        ),
        migrations.AddField(
            model_name='destination',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.location', verbose_name='Локация'),
        ),
        migrations.AddField(
            model_name='destination',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.region', verbose_name='Регион'),
        ),
        migrations.CreateModel(
            name='CountryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='countries', verbose_name='Загрузить изображение')),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tour.country', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Изображение страны',
                'verbose_name_plural': 'Изображение стран',
                'db_table': 'country_images',
            },
        ),
        migrations.AddField(
            model_name='country',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tour.location', verbose_name='Локация'),
        ),
        migrations.CreateModel(
            name='CityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cities', verbose_name='Загрузить изображение')),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tour.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Изображение города',
                'verbose_name_plural': 'Изображение городов',
                'db_table': 'city_images',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tour.location', verbose_name='Локация'),
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.region'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(verbose_name='Дата заезда')),
                ('check_out', models.DateField(verbose_name='Дата выезда')),
                ('status', models.CharField(choices=[('paid', 'paid'), ('booked', 'booked'), ('conditionally', 'conditionally')], max_length=13, verbose_name='Статус')),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='tour.accommodation', verbose_name='Размещение')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.destination', verbose_name='Пункт')),
            ],
            options={
                'verbose_name': 'Активность',
                'verbose_name_plural': 'Активности',
                'db_table': 'activity',
            },
        ),
        migrations.CreateModel(
            name='AccommodationRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_value', models.PositiveIntegerField(default=0)),
                ('total_ratings', models.PositiveIntegerField(default=0)),
                ('target_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.accommodation', verbose_name='Отель')),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинги',
            },
        ),
        migrations.CreateModel(
            name='AccommodationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='accommodations', verbose_name='Загрузить изображение')),
                ('accommodation_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tour.accommodation', verbose_name='Отель')),
            ],
            options={
                'verbose_name': 'Изображение отеля',
                'verbose_name_plural': 'Изображение отелей',
                'db_table': 'accommodation_images',
            },
        ),
        migrations.AddField(
            model_name='accommodation',
            name='city',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.DO_NOTHING, to='tour.city', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='location',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.DO_NOTHING, to='tour.location', verbose_name='Локация'),
        ),
    ]
