# Generated by Django 4.2.3 on 2023-08-23 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'verbose_name': 'Отель', 'verbose_name_plural': 'Отели'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Область', 'verbose_name_plural': 'Области'},
        ),
        migrations.AlterField(
            model_name='hotel',
            name='city',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.DO_NOTHING, to='tour.hotel', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название отели'),
        ),
    ]
