# Generated by Django 4.2.3 on 2024-12-29 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accommodation', '0002_initial'),
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='tourphotos',
            name='tour_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.tour', verbose_name='Тур'),
        ),
        migrations.AddField(
            model_name='tourday',
            name='accommodation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accommodation.accommodation', verbose_name='Проживание'),
        ),
        migrations.AddField(
            model_name='tourday',
            name='destination',
            field=models.ManyToManyField(to='tour.destination', verbose_name='Пункты'),
        ),
        migrations.AddField(
            model_name='tourday',
            name='meals',
            field=models.ManyToManyField(null=True, to='categories.meal', verbose_name='Питание'),
        ),
        migrations.AddField(
            model_name='tourday',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.tour'),
        ),
        migrations.AddField(
            model_name='tourcommentphotos',
            name='comment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tour.tourcomment', verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='tourcomment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tour.tourcomment'),
        ),
        migrations.AddField(
            model_name='tourcomment',
            name='tour_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.tour', verbose_name='Тур'),
        ),
        migrations.AddField(
            model_name='tourcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='tour',
            name='excludes',
            field=models.ManyToManyField(to='categories.excludes', verbose_name='Исключения'),
        ),
        migrations.AddField(
            model_name='tour',
            name='health_information',
            field=models.ManyToManyField(to='categories.health', verbose_name='Информация о здоровье'),
        ),
        migrations.AddField(
            model_name='tour',
            name='includes',
            field=models.ManyToManyField(to='categories.includes', verbose_name='Включения'),
        ),
        migrations.AddField(
            model_name='tour',
            name='personal_gear',
            field=models.ManyToManyField(to='categories.gear', verbose_name='Снаряжение'),
        ),
        migrations.AddField(
            model_name='tour',
            name='type_of',
            field=models.ManyToManyField(to='tour.typeoftour', verbose_name='Сложность'),
        ),
        migrations.AddField(
            model_name='tour',
            name='visa_information',
            field=models.ManyToManyField(to='categories.visa', verbose_name='Информация о визе'),
        ),
        migrations.AddField(
            model_name='regionimage',
            name='region_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tour.region', verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='region',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.country'),
        ),
        migrations.AddField(
            model_name='region',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tour.location', verbose_name='Локация'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='accommodation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accommodation.accommodation', verbose_name='Проживание'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='entertainment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='categories.entertainment', verbose_name='Развлечения'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='meals',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='categories.meal', verbose_name='Еда'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='tour_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.tour', verbose_name='Тур'),
        ),
        migrations.AddField(
            model_name='destinationrating',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='tour.destination'),
        ),
        migrations.AddField(
            model_name='destinationimages',
            name='destination_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tour.destination', verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='destination',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='destination',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.location', verbose_name='Локация'),
        ),
        migrations.AddField(
            model_name='destination',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.region', verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='countryimage',
            name='country_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tour.country', verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='country',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tour.location', verbose_name='Локация'),
        ),
        migrations.AddField(
            model_name='cityimage',
            name='city_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tour.city', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='city',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tour.location', verbose_name='Локация'),
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.region'),
        ),
        migrations.AddField(
            model_name='booking',
            name='accommodation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='accommodation.accommodation', verbose_name='Размещение'),
        ),
        migrations.AddField(
            model_name='activity',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='tour.destination', verbose_name='Пункт'),
        ),
    ]
