# Generated by Django 4.2.3 on 2025-01-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='countries',
        ),
        migrations.AddField(
            model_name='tour',
            name='countries',
            field=models.ManyToManyField(limit_choices_to={'type__in': ['country']}, to='tour.location'),
        ),
    ]
