# Generated by Django 4.2.3 on 2025-03-08 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinationimages',
            name='destination_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='destination_image', to='tour.destination', verbose_name='Страна'),
        ),
    ]
