# Generated by Django 4.2.3 on 2023-08-23 10:45

from django.db import migrations, models
import django.db.models.deletion
import django_admin_geomap


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_alter_city_options_alter_hotel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название отели')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Отель',
                'verbose_name_plural': 'Отели',
            },
        ),
        migrations.CreateModel(
            name='AccommodationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='accommodations', verbose_name='Загрузить изображение')),
            ],
            options={
                'verbose_name': 'Изображение отеля',
                'verbose_name_plural': 'Изображение отелей',
                'db_table': 'accommodation_images',
            },
        ),
        migrations.CreateModel(
            name='CityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cities', verbose_name='Загрузить изображение')),
            ],
            options={
                'verbose_name': 'Изображение города',
                'verbose_name_plural': 'Изображение городов',
                'db_table': 'city_images',
            },
        ),
        migrations.CreateModel(
            name='CountryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='countries', verbose_name='Загрузить изображение')),
            ],
            options={
                'verbose_name': 'Изображение страны',
                'verbose_name_plural': 'Изображение стран',
                'db_table': 'country_images',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название места')),
                ('lon', models.FloatField(verbose_name='Долгота')),
                ('lat', models.FloatField(verbose_name='Широта')),
            ],
            bases=(models.Model, django_admin_geomap.GeoItem),
        ),
        migrations.CreateModel(
            name='RegionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='regions', verbose_name='Загрузить изображение')),
            ],
            options={
                'verbose_name': 'Изображение региона',
                'verbose_name_plural': 'Изображение регионов',
                'db_table': 'region_images',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='description',
            field=models.TextField(default=3, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='description',
            field=models.TextField(default=3, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
        migrations.AddField(
            model_name='accommodation',
            name='city',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.DO_NOTHING, to='tour.city', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tour.accommodationimage', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='point',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.DO_NOTHING, to='tour.location', verbose_name='Локация'),
        ),
        migrations.AddField(
            model_name='city',
            name='image',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.DO_NOTHING, to='tour.cityimage', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='country',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tour.countryimage', verbose_name='Изображения'),
        ),
        migrations.AlterField(
            model_name='region',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tour.regionimage', verbose_name='Изображение'),
        ),
    ]
