# Generated by Django 5.0.3 on 2024-03-26 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={'verbose_name': 'Тур', 'verbose_name_plural': 'Туры'},
        ),
        migrations.AddField(
            model_name='accommodation',
            name='price',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=5, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='tour',
            table='tour',
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(verbose_name='Дата заезда')),
                ('check_out', models.DateField(verbose_name='Дата выезда')),
                ('status', models.CharField(choices=[('paid', 'paid'), ('booked', 'booked'), ('conditionally', 'conditionally')], max_length=13, verbose_name='Статус')),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='tour.accommodation', verbose_name='Размещение')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
            },
        ),
    ]
