# Generated by Django 4.2.3 on 2025-03-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_alter_destinationimages_destination_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeoftour',
            name='icon',
            field=models.FileField(null=True, upload_to='icons', verbose_name='Иконка'),
        ),
        migrations.RemoveField(
            model_name='tourday',
            name='entertainment',
        ),
        migrations.AlterField(
            model_name='tourday',
            name='meals',
            field=models.CharField(choices=[('Звтрак', 'breakfast'), ('Обед', 'lunch'), ('Ланч бокс', 'lunch-box'), ('Ужин', 'dinner')], max_length=50, null=True, verbose_name='Питание'),
        ),
        migrations.AddField(
            model_name='tourday',
            name='entertainment',
            field=models.ManyToManyField(blank=True, related_name='entertainment', to='tour.activity', verbose_name='Развлечения'),
        ),
    ]
