# Generated by Django 4.2.3 on 2023-09-11 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_accommodationrating_remove_accommodation_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodationrating',
            name='target_object_id',
        ),
    ]
