# Generated by Django 4.2.3 on 2025-01-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('tour', '0002_remove_tour_countries_tour_countries'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typeoftour',
            options={'verbose_name': 'Тип Тура', 'verbose_name_plural': 'Типы Туров'},
        ),
        migrations.AlterField(
            model_name='tour',
            name='excludes',
            field=models.ManyToManyField(blank=True, to='categories.excludes', verbose_name='Исключения'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='health_information',
            field=models.ManyToManyField(blank=True, to='categories.health', verbose_name='Информация о здоровье'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='includes',
            field=models.ManyToManyField(blank=True, to='categories.includes', verbose_name='Включения'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Примечания'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='personal_gear',
            field=models.ManyToManyField(blank=True, to='categories.gear', verbose_name='Снаряжение'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='total_distance',
            field=models.FloatField(blank=True, verbose_name='Итоговая дистанция'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_types',
            field=models.ManyToManyField(blank=True, to='tour.typeoftour'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='video',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на видео'),
        ),
        migrations.AlterField(
            model_name='typeoftour',
            name='type',
            field=models.CharField(max_length=100, verbose_name='Тип'),
        ),
    ]
