# Generated by Django 4.2.3 on 2023-09-13 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_remove_accommodationrating_target_object_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countryimage',
            old_name='Country_id',
            new_name='country_id',
        ),
    ]
