# Generated by Django 5.0.3 on 2024-03-29 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_alter_tour_options_accommodation_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itinerary',
            options={'verbose_name': 'Маршрут', 'verbose_name_plural': 'Маршруты'},
        ),
        migrations.AlterModelOptions(
            name='tourcomment',
            options={'verbose_name': 'Комментарий к туру', 'verbose_name_plural': 'Комментарии к туру'},
        ),
        migrations.AlterModelTable(
            name='itinerary',
            table='itinerary',
        ),
        migrations.AlterModelTable(
            name='tourcomment',
            table='tour_comments',
        ),
    ]
