# Generated by Django 4.2.3 on 2025-03-08 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_typeoftour_icon_remove_tourday_entertainment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='icon',
        ),
    ]
