# Generated by Django 4.2.3 on 2025-01-30 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0002_initial'),
        ('tour', '0003_alter_typeoftour_options_alter_tour_excludes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourday',
            name='accommodation',
        ),
        migrations.AlterField(
            model_name='tourday',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='tour.tour'),
        ),
        migrations.AddField(
            model_name='tourday',
            name='accommodation',
            field=models.ManyToManyField(blank=True, related_name='accomodation_for_tour', to='accommodation.accommodation', verbose_name='Проживание'),
        ),
    ]
