# Generated by Django 5.0.3 on 2024-04-15 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_remove_tour_destinations_tour_destinations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='geomap_latitude',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='geomap_longitude',
        ),
    ]
