# Generated by Django 4.2.3 on 2023-08-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_accommodation_accommodationimage_cityimage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Локация', 'verbose_name_plural': 'Локации'},
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название локации'),
        ),
        migrations.AlterModelTable(
            name='accommodation',
            table='accommodations',
        ),
        migrations.AlterModelTable(
            name='city',
            table='cities',
        ),
        migrations.AlterModelTable(
            name='country',
            table='countries',
        ),
        migrations.AlterModelTable(
            name='location',
            table='locations',
        ),
        migrations.AlterModelTable(
            name='region',
            table='regions',
        ),
    ]
