# Generated by Django 4.2.3 on 2025-03-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0002_initial'),
        ('tour', '0004_remove_tourday_accommodation_alter_tourday_tour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='icon',
            field=models.ImageField(default=1, upload_to='media/icons', verbose_name='иконка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tourday',
            name='accommodation',
            field=models.ManyToManyField(blank=True, related_name='accommodation', to='accommodation.accommodation', verbose_name='Проживание'),
        ),
    ]
