# Generated by Django 4.2.3 on 2025-01-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_tour_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='duration_date',
            new_name='days_count',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='location',
            name='type',
            field=models.CharField(choices=[('country', 'Страна'), ('region', 'Область'), ('city', 'Город'), ('destination', 'Пункт')], default=3, max_length=100, verbose_name='Тип локации'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='promotion',
            field=models.PositiveSmallIntegerField(default=0, help_text='Указывайте в дробном виде 0.1', verbose_name='Скидка'),
        ),
    ]
