# Generated by Django 5.0.3 on 2024-03-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('tour', '0004_alter_itinerary_options_alter_tourcomment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='excludes',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='health_information',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='includes',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='personal_gear',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='type_of',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='visa_information',
        ),
        migrations.AddField(
            model_name='tour',
            name='excludes',
            field=models.ManyToManyField(to='categories.excludes', verbose_name='Исключения'),
        ),
        migrations.AddField(
            model_name='tour',
            name='health_information',
            field=models.ManyToManyField(to='categories.health', verbose_name='Информация о здоровье'),
        ),
        migrations.AddField(
            model_name='tour',
            name='includes',
            field=models.ManyToManyField(to='categories.includes', verbose_name='Включения'),
        ),
        migrations.AddField(
            model_name='tour',
            name='personal_gear',
            field=models.ManyToManyField(to='categories.gear', verbose_name='Снаряжение'),
        ),
        migrations.AddField(
            model_name='tour',
            name='type_of',
            field=models.ManyToManyField(to='tour.typeoftour', verbose_name='Сложность'),
        ),
        migrations.AddField(
            model_name='tour',
            name='visa_information',
            field=models.ManyToManyField(to='categories.visa', verbose_name='Информация о визе'),
        ),
    ]
