# Generated by Django 4.2.3 on 2023-08-23 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_alter_location_options_alter_location_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accommodation',
            old_name='point',
            new_name='location',
        ),
        migrations.AddField(
            model_name='city',
            name='location',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.DO_NOTHING, to='tour.location', verbose_name='Локация'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='location',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.DO_NOTHING, to='tour.location', verbose_name='Локация'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='region',
            name='location',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.DO_NOTHING, to='tour.location', verbose_name='Локация'),
            preserve_default=False,
        ),
    ]
