# Generated by Django 4.2.3 on 2023-10-23 10:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_rename_country_id_countryimage_country_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название тура')),
            ],
        ),
        migrations.CreateModel(
            name='TourComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TourCommentPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='commentImages', verbose_name='Загрузить изображение')),
            ],
            options={
                'verbose_name': 'Изображение комментария',
                'verbose_name_plural': 'Изображение комментариев',
                'db_table': 'comment_images',
            },
        ),
        migrations.CreateModel(
            name='TourRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
                ('tour_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.tour', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Рейтинг тура',
                'verbose_name_plural': 'Рейтинги туров',
                'db_table': 'tour_rating',
            },
        ),
    ]
