# Generated by Django 4.2.3 on 2024-05-04 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0002_alter_accommodationimage_table'),
        ('categories', '0001_initial'),
        ('tour', '0005_remove_accommodation_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(verbose_name='Номер дня')),
                ('description', models.TextField(verbose_name='Описание')),
                ('entertainment', models.CharField(max_length=255, verbose_name='Развлечения')),
                ('details', models.TextField(verbose_name='Детали')),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodation.accommodation', verbose_name='Проживание')),
                ('locations', models.ManyToManyField(to='tour.location', verbose_name='Локации')),
                ('meals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.meal', verbose_name='Питание')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_days', to='tour.tour', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'День тура',
                'verbose_name_plural': 'Дни тура',
            },
        ),
    ]
