# Generated by Django 4.2.3 on 2023-10-23 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0005_tour_tourcomment_tourcommentphotos_tourrating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tourrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='tourcommentphotos',
            name='comment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tour.tourcomment', verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='tourcomment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tour.tourcomment'),
        ),
        migrations.AddField(
            model_name='tourcomment',
            name='tour_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.tour', verbose_name='Тур'),
        ),
        migrations.AddField(
            model_name='tourcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
