# Generated by Django 4.2.3 on 2025-03-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0005_activity_icon_alter_tourday_accommodation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='destination',
        ),
        migrations.AlterField(
            model_name='activity',
            name='icon',
            field=models.ImageField(upload_to='icons', verbose_name='иконка'),
        ),
        migrations.AddField(
            model_name='activity',
            name='destination',
            field=models.ManyToManyField(to='tour.destination', verbose_name='Пункты'),
        ),
    ]
