# Generated by Django 4.2.3 on 2025-03-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0005_alter_tourcommentphotos_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourday',
            name='day_number',
        ),
        migrations.AddField(
            model_name='tourday',
            name='name',
            field=models.CharField(default=3, max_length=255, verbose_name='Наименование'),
            preserve_default=False,
        ),
    ]
