# Generated by Django 4.2.3 on 2024-12-26 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('accommodation', '0002_alter_accommodationimage_table'),
        ('tour', '0005_remove_accommodation_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
        migrations.RemoveField(
            model_name='tour',
            name='destinations',
        ),
        migrations.CreateModel(
            name='TourDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(verbose_name='Номер дня')),
                ('description', models.TextField(verbose_name='Описание')),
                ('car_range', models.PositiveIntegerField(verbose_name='Длина пути на машине')),
                ('tracking_range', models.PositiveIntegerField(verbose_name='Длина пути пешком')),
                ('height_difference', models.CharField(max_length=255, verbose_name='Перепад высоты')),
                ('weather', models.CharField(max_length=255, verbose_name='Погода')),
                ('entertainment', models.CharField(max_length=255, verbose_name='Развлечения')),
                ('details', models.TextField(verbose_name='Детали')),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodation.accommodation', verbose_name='Проживание')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.destination', verbose_name='Пункты')),
                ('locations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.location', verbose_name='Локации')),
                ('meals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.meal', verbose_name='Питание')),
            ],
            options={
                'verbose_name': 'День тура',
                'verbose_name_plural': 'Дни тура',
            },
        ),
        migrations.AddField(
            model_name='tour',
            name='destinations',
            field=models.ManyToManyField(related_name='destinations', to='tour.destination', verbose_name='Пункты'),
        ),
    ]
