# Generated by Django 4.2.3 on 2023-08-23 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0005_rename_point_accommodation_location_city_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodation',
            name='image',
        ),
        migrations.AddField(
            model_name='accommodationimage',
            name='accommodation_id',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.DO_NOTHING, to='tour.accommodation', verbose_name='Отель'),
            preserve_default=False,
        ),
    ]
