# Generated by Django 4.2.3 on 2025-01-05 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0005_rename_duration_date_tour_days_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='location',
            field=models.ForeignKey(limit_choices_to={'name__in': ['country']}, on_delete=django.db.models.deletion.CASCADE, to='tour.location'),
        ),
    ]
