# Generated by Django 5.0.3 on 2024-03-29 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0006_remove_tour_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='geomap_latitude',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='tour.location', verbose_name='Локация'),
            preserve_default=False,
        ),
    ]
