# Generated by Django 4.2.3 on 2025-03-05 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0006_alter_activity_icon'),
    ]
    operations = [
        migrations.AddField(
            model_name='Activity',
            name='icon',
            field=models.ImageField(upload_to='icons', null=True,verbose_name='Иконка', blank=True),
        )]

