# Generated by Django 4.2.3 on 2023-08-23 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0006_remove_accommodation_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='image',
        ),
        migrations.RemoveField(
            model_name='country',
            name='image',
        ),
        migrations.RemoveField(
            model_name='region',
            name='image',
        ),
        migrations.AddField(
            model_name='cityimage',
            name='city_id',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.DO_NOTHING, to='tour.city', verbose_name='Город'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='countryimage',
            name='Country_id',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.DO_NOTHING, to='tour.country', verbose_name='Страна'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regionimage',
            name='region_id',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.DO_NOTHING, to='tour.region', verbose_name='Регион'),
            preserve_default=False,
        ),
    ]
