# Generated by Django 4.2.3 on 2024-05-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0006_tourday'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
    ]
