# Generated by Django 4.2.3 on 2025-01-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0006_alter_tour_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='type_of',
        ),
        migrations.AddField(
            model_name='tour',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Легкий'), ('middle', 'Средний'), ('hard', 'Сложный')], default=3, max_length=20, verbose_name='Сложность'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='tour',
            name='visa_information',
        ),
        migrations.AddField(
            model_name='tour',
            name='visa_information',
            field=models.CharField(choices=[('электронная', 'Электронная виза'), ('обыкновенная ', 'Обыкновенная  виза'), ('транзитная', 'Транзитная виза'), ('временная', 'Виза временно проживающего лица')], default=3, max_length=255, verbose_name='Информация о визе'),
            preserve_default=False,
        ),
    ]
