# Generated by Django 4.2.3 on 2025-04-29 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0006_remove_tourday_day_number_tourday_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourdayorder',
            options={'ordering': ['day_number'], 'verbose_name': 'День тура', 'verbose_name_plural': 'Дни тура'},
        ),
        migrations.AddField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tourday',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='Детали'),
        ),
        migrations.AlterField(
            model_name='tourday',
            name='meals',
            field=models.CharField(choices=[('breakfast', 'Звтрак'), ('lunch', 'Обед'), ('lunch-box', 'Ланч бокс'), ('dinner', 'Ужин')], max_length=50, null=True, verbose_name='Питание'),
        ),
        migrations.AlterField(
            model_name='tourday',
            name='weather',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Погода'),
        ),
        migrations.AlterField(
            model_name='tourday',
            name='weather_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата погоды'),
        ),
        migrations.AlterField(
            model_name='tourdayorder',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.tour', verbose_name='Тур'),
        ),
        migrations.AlterField(
            model_name='tourdayorder',
            name='tour_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.tourday', verbose_name='День тура'),
        ),
    ]
