# Generated by Django 4.2.3 on 2024-12-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('tour', '0006_destination_active_remove_tour_destinations_tourday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourday',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='tourday',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='tourday',
            name='meals',
        ),
        migrations.AddField(
            model_name='tourday',
            name='destination',
            field=models.ManyToManyField(to='tour.destination', verbose_name='Пункты'),
        ),
        migrations.AddField(
            model_name='tourday',
            name='locations',
            field=models.ManyToManyField(to='tour.location', verbose_name='Локации'),
        ),
        migrations.AddField(
            model_name='tourday',
            name='meals',
            field=models.ManyToManyField(to='categories.meal', verbose_name='Питание'),
        ),
    ]
