# Generated by Django 4.2.3 on 2025-01-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0007_remove_tour_type_of_tour_difficulty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='location',
        ),
        migrations.AddField(
            model_name='tour',
            name='countries',
            field=models.ManyToManyField(limit_choices_to={'type__in': ['country']}, to='tour.location'),
        ),
    ]
