# Generated by Django 4.2.3 on 2024-12-26 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0007_remove_tourday_destination_remove_tourday_locations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourday',
            name='locations',
        ),
    ]
