# Generated by Django 4.2.3 on 2024-05-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0007_destination_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='destinations',
        ),
        migrations.AddField(
            model_name='tour',
            name='destinations',
            field=models.ManyToManyField(related_name='destinations', to='tour.destination', verbose_name='Пункты'),
        ),
    ]
