# Generated by Django 4.2.3 on 2025-04-30 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('tour', '0007_alter_tourdayorder_options_activity_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='meals',
        ),
        migrations.RemoveField(
            model_name='tourday',
            name='meals',
        ),
        migrations.AddField(
            model_name='itinerary',
            name='meals',
            field=models.ManyToManyField(related_name='itenerary_meal', to='categories.meal', verbose_name='Еда'),
        ),
        migrations.AddField(
            model_name='tourday',
            name='meals',
            field=models.ManyToManyField(max_length=50, related_name='tour_meals', to='categories.meal', verbose_name='Питание'),
        ),
    ]
