# Generated by Django 5.0.3 on 2024-03-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0007_tour_geomap_latitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='geomap_longitude',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='geomap_latitude',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Широта'),
        ),
    ]
