# Generated by Django 4.2.3 on 2025-04-30 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0008_remove_itinerary_meals_remove_tourday_meals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourday',
            name='total_distance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Дистанция'),
        ),
        migrations.CreateModel(
            name='TransportDistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_type', models.CharField(choices=[('car', 'Car'), ('walk', 'Walk'), ('horse', 'Horse'), ('ski', 'Ski'), ('ski', 'Ski'), ('boat', 'Boat'), ('plane', 'Plane'), ('helicopter', 'Helicopter'), ('train', 'Train')], max_length=10)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tour_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distances', to='tour.tourday')),
            ],
        ),
    ]
