# Generated by Django 4.2.3 on 2024-12-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0008_remove_tour_destinations_tour_destinations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='destinations',
            field=models.ManyToManyField(related_name='tour_id', to='tour.destination', verbose_name='Пункты'),
        ),
    ]
