# Generated by Django 5.0.3 on 2024-04-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0008_tour_geomap_longitude_alter_tour_geomap_latitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Активности')),
            ],
            options={
                'verbose_name': 'Активность',
                'verbose_name_plural': 'Активности',
                'db_table': 'activity',
            },
        ),
        migrations.AddField(
            model_name='tour',
            name='short_description',
            field=models.TextField(default=3, verbose_name='Краткое описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='activities',
            field=models.ManyToManyField(to='tour.activity', verbose_name='Активности'),
        ),
    ]
