# Generated by Django 5.0.3 on 2024-04-03 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0009_activity_tour_short_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активность'),
        ),
        migrations.CreateModel(
            name='DestinationRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='Рейтинг')),
                ('destination_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.destination')),
            ],
            options={
                'verbose_name': 'Рейтинг пункта',
                'verbose_name_plural': 'Рейтинги пунктов',
                'db_table': 'destination_rating',
            },
        ),
    ]
