# Generated by Django 4.2.3 on 2025-01-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0010_remove_tour_countries_tour_countries'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='days_count',
            new_name='duration',
        ),
        migrations.AlterField(
            model_name='tour',
            name='difficulty',
            field=models.CharField(choices=[('1', 'Легкий'), ('2', 'Средний'), ('3', 'Сложный')], max_length=20, verbose_name='Сложность'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_types',
            field=models.ManyToManyField(to='tour.typeoftour'),
        ),
    ]
