# Generated by Django 5.0.3 on 2024-04-04 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0010_destination_active_destinationrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinationrating',
            name='destination_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='tour.destination'),
        ),
    ]
