# Generated by Django 4.2.3 on 2025-04-30 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0010_alter_transportdistance_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='map',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на карту'),
        ),
    ]
