# Generated by Django 5.0.3 on 2024-04-10 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0011_alter_destinationrating_destination_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destinationrating',
            old_name='destination_id',
            new_name='destination',
        ),
    ]
