# Generated by Django 5.0.3 on 2024-04-11 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0012_rename_destination_id_destinationrating_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinationrating',
            name='value',
            field=models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Рейтинг'),
        ),
    ]
