# Generated by Django 5.0.3 on 2024-04-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0013_alter_destinationrating_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='destinations',
            field=models.ManyToManyField(related_name='tour', to='tour.destination', verbose_name='Пункты'),
        ),
    ]
