version: '3.9'

services:
  web:
    build: ./main
    container_name: nomadstravel-web
    volumes:
      - ./main:/main
      - static_volume:/main/static
      - media_volume:/main/media
    env_file:
      - main/.env
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    container_name: nomadstravel-nginx
    ports:
      - "8000:80"
    volumes:
      - ./main/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/main/static
      - media_volume:/main/media
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
