# Generated by Django 4.2.3 on 2025-03-05 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('photo', models.ImageField(upload_to='employees/', verbose_name='Фото')),
                ('description', models.TextField(verbose_name='Описание')),
                ('slogan', models.CharField(max_length=200, verbose_name='Слоган')),
                ('slogan_author', models.CharField(blank=True, max_length=100, verbose_name='Автор слогана')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('phone', models.CharField(help_text='только в международном формате, например +996***', max_length=20, verbose_name='Номер телефона')),
                ('telegram', models.CharField(blank=True, max_length=50, verbose_name='Telegram')),
                ('passport_scan', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Скан паспорта')),
                ('driver_license', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Скан вод. удостоверения')),
                ('birth_place', models.CharField(max_length=100, verbose_name='Место рождения')),
                ('education', models.TextField(verbose_name='Образование')),
                ('languages', models.JSONField(verbose_name='Языки')),
                ('experience', models.IntegerField(verbose_name='Опыт')),
                ('history_knowledge_level', models.CharField(max_length=50, verbose_name='Уровень знания истории')),
                ('driving_experience', models.IntegerField(default=0, verbose_name='Опыт вождения')),
            ],
            options={
                'verbose_name': 'Гид',
                'verbose_name_plural': 'Гиды',
            },
        ),
        migrations.CreateModel(
            name='OtherEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('photo', models.ImageField(upload_to='employees/', verbose_name='Фото')),
                ('description', models.TextField(verbose_name='Описание')),
                ('slogan', models.CharField(max_length=200, verbose_name='Слоган')),
                ('slogan_author', models.CharField(blank=True, max_length=100, verbose_name='Автор слогана')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('phone', models.CharField(help_text='только в международном формате, например +996***', max_length=20, verbose_name='Номер телефона')),
                ('telegram', models.CharField(blank=True, max_length=50, verbose_name='Telegram')),
                ('passport_scan', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Скан паспорта')),
                ('driver_license', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Скан вод. удостоверения')),
                ('birth_place', models.CharField(max_length=100, verbose_name='Место рождения')),
                ('education', models.TextField(verbose_name='Образование')),
                ('languages', models.JSONField(verbose_name='Языки')),
                ('experience', models.IntegerField(verbose_name='Опыт')),
                ('role', models.CharField(max_length=100, verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Сторудник',
                'verbose_name_plural': 'Другие сотрудники',
            },
        ),
        migrations.CreateModel(
            name='HotelEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('photo', models.ImageField(upload_to='employees/', verbose_name='Фото')),
                ('description', models.TextField(verbose_name='Описание')),
                ('slogan', models.CharField(max_length=200, verbose_name='Слоган')),
                ('slogan_author', models.CharField(blank=True, max_length=100, verbose_name='Автор слогана')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('phone', models.CharField(help_text='только в международном формате, например +996***', max_length=20, verbose_name='Номер телефона')),
                ('telegram', models.CharField(blank=True, max_length=50, verbose_name='Telegram')),
                ('passport_scan', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Скан паспорта')),
                ('driver_license', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Скан вод. удостоверения')),
                ('birth_place', models.CharField(max_length=100, verbose_name='Место рождения')),
                ('education', models.TextField(verbose_name='Образование')),
                ('languages', models.JSONField(verbose_name='Языки')),
                ('experience', models.IntegerField(verbose_name='Опыт')),
                ('booking_name', models.CharField(max_length=100, verbose_name='Имя Фамилия сотрудника для брони')),
                ('contact_for_clients', models.CharField(max_length=100, verbose_name='Контакты')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodation.accommodation')),
            ],
            options={
                'verbose_name': 'Работник отеля',
                'verbose_name_plural': 'Работники отелей',
            },
        ),
    ]
