# Generated by Django 4.2.3 on 2025-03-04 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_guide_otheremployee_hotelemployee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guide',
            options={'verbose_name': 'Гид', 'verbose_name_plural': 'Гиды'},
        ),
        migrations.AlterModelOptions(
            name='hotelemployee',
            options={'verbose_name': 'Работник отеля', 'verbose_name_plural': 'Работники отелей'},
        ),
        migrations.AlterModelOptions(
            name='otheremployee',
            options={'verbose_name': 'Сторудник', 'verbose_name_plural': 'Другие сотрудники'},
        ),
    ]
