# Generated by Django 4.2.3 on 2024-12-29 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('main_image', models.ImageField(upload_to='accomodation', verbose_name='Главное изображение')),
            ],
            options={
                'verbose_name': 'Размещение',
                'verbose_name_plural': 'Размещения',
                'db_table': 'accommodation',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, verbose_name='Тип')),
                ('size', models.PositiveSmallIntegerField(verbose_name='Размер')),
                ('mini_bar', models.BooleanField(default=False, verbose_name='Мини бар')),
                ('tv', models.BooleanField(default=False, verbose_name='Телевизор')),
                ('bed', models.CharField(max_length=255, verbose_name='Кровать')),
                ('bath', models.CharField(max_length=255, verbose_name='Ванная')),
                ('toilet', models.BooleanField(default=False, verbose_name='Туалет')),
                ('ac', models.BooleanField(default=False, verbose_name='Кондиционер')),
                ('window', models.CharField(max_length=255, verbose_name='Окно')),
                ('wifi', models.BooleanField(default=False, verbose_name='WIFI')),
                ('fridge', models.BooleanField(default=False, verbose_name='Холодильник')),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodation.accommodation')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
                'db_table': 'room',
            },
        ),
        migrations.CreateModel(
            name='AccommodationRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='Рейтинг')),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodation.accommodation', verbose_name='Резмещение')),
            ],
            options={
                'verbose_name': 'Рейтинг места размещения',
                'verbose_name_plural': 'Рейтинги мест размещения',
                'db_table': 'accommodation_rating',
            },
        ),
        migrations.CreateModel(
            name='AccommodationIncludes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast', models.BooleanField(default=False, verbose_name='Завтрак')),
                ('indoor_swimming_pool', models.BooleanField(default=False, verbose_name='Бассейн')),
                ('airport_shuttle', models.BooleanField(default=False, verbose_name='Трансфер до аэропорта')),
                ('non_smoking_rooms', models.BooleanField(default=False, verbose_name='Комната для некурящих')),
                ('fitness_center', models.BooleanField(default=False, verbose_name='Фитнесс')),
                ('free_wifi', models.BooleanField(default=False, verbose_name='Беслатный wifi')),
                ('room_service', models.BooleanField(default=False, verbose_name='Обслуживание номеров')),
                ('free_parking', models.BooleanField(default=False, verbose_name='Бесплатная парковка')),
                ('tea_maker_in_room', models.BooleanField(default=False, verbose_name='Чайник/кофеварка во всех номерах')),
                ('bar', models.BooleanField(default=False, verbose_name='Бар')),
                ('laundry', models.BooleanField(default=False, verbose_name='Прачечная')),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodation.accommodation')),
            ],
            options={
                'verbose_name': 'Включение',
                'verbose_name_plural': 'Включения',
                'db_table': 'accommodation_includes',
            },
        ),
        migrations.CreateModel(
            name='AccommodationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='accommodations', verbose_name='Загрузить изображение')),
                ('accommodation_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accommodation.accommodation', verbose_name='Отель')),
            ],
            options={
                'verbose_name': 'Изображение отеля',
                'verbose_name_plural': 'Изображение отелей',
                'db_table': 'accommodation_image',
            },
        ),
    ]
