# Generated by Django 5.0.3 on 2024-04-16 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='accommodationimage',
            table='accommodation_image',
        ),
    ]
