# Generated by Django 4.2.3 on 2025-05-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='elevation',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5, verbose_name='Высота над у.м.'),
        ),
    ]
