# Generated by Django 4.2.3 on 2025-05-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0003_accommodation_elevation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='elevation',
            field=models.FloatField(default=0, verbose_name='Высота над у.м.'),
        ),
    ]
